## source: registry https://registry.comfy.org/
# [[custom_nodes]]
# node_id = "comfyui-impact-pack"
# version = "latest"             # option: latest, nightly, vX.Y.Z

## source: git repo
## if node_id provided, url will be ignored
# [[custom_nodes]]
# url = "https://github.com/ltdrdata/ComfyUI-Impact-Pack"
# branch = "main" # optional, use specify branch
# script = "post-install-impact-pack.sh" # optional, store it in scripts/post-install-node

# [[models]]
# url = "https://huggingface.co/stabilityai/stable-diffusion-xl-base-1.0/resolve/main/sd_xl_base_1.0.safetensors"
# dir = "models/checkpoints/sdxl"
# filename = "sd_xl_base_1.0.safetensors"

# [[models]]
# url = "https://huggingface.co/madebyollin/sdxl-vae-fp16-fix/resolve/main/sdxl_vae.safetensors"
# dir = "models/vae/sdxl"
# filename = "sdxl_vae_fp16_fix.safetensors"

# [[models]]
# url = "https://civitai.com/api/download/models/30163?type=Model&format=SafeTensor&size=full&fp=fp16"
# dir = "models/checkpoints/sd15"
# filename = "AnythingV5_v5PrtRE.safetensors"
