name: Update Docker Hub Description
on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/update-dockerhub-desc.yml
      - README.md

jobs:
  update-dockerhub-desc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: jimlee2048/comfyui-docker
          short-description: ${{ github.event.repository.description }}
          enable-url-completion: true
